/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JOptionPane;
import model.DaoVeiculo;
import model.Pneu;
import model.DaoPneu;

/**
 *
 * @author humberto
 */
public class PneuView extends javax.swing.JFrame {
    DaoVeiculo daoVeiculo;
    Pneu pneu;
    DaoPneu daoPneu;
    /**
     * Creates new form VeiculoView
     */
    public PneuView() {
        initComponents();
        daoVeiculo = new DaoVeiculo();
        this.atualizarTabela();
    }

    public void atualizarTabela(){
        jtPneus.setModel(new VeiculoTableModel(daoVeiculo.buscarTodos()));
    }
    
    public void limparCampos(){
        tfID.setText("");
        tfSerie.setText("");
        tfCor.setText("");
        tfCod.setText("");
        tfEstado.setText("");
        btExcluir.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFiltro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfSerie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPneus = new javax.swing.JTable();
        tfID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCor = new javax.swing.JTextField();
        tfCod = new javax.swing.JTextField();
        tfEstado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rbMarca = new javax.swing.JRadioButton();
        rbModelo = new javax.swing.JRadioButton();
        tfFiltro = new javax.swing.JTextField();
        btFiltrar = new javax.swing.JButton();
        btListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Serie");
        jLabel1.setName(""); // NOI18N

        tfSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSerieActionPerformed(evt);
            }
        });

        jtPneus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtPneus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPneusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPneus);

        tfID.setEditable(false);
        tfID.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setText("Código:");

        jLabel3.setText("Cor:");

        tfEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEstadoFocusLost(evt);
            }
        });

        jLabel4.setText("Cod");

        jLabel5.setText("Estado");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jLabel6.setText("Filtrar por:");

        bgFiltro.add(rbMarca);
        rbMarca.setText("Marca");

        bgFiltro.add(rbModelo);
        rbModelo.setText("Modelo");
        rbModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbModeloActionPerformed(evt);
            }
        });

        tfFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFiltroActionPerformed(evt);
            }
        });

        btFiltrar.setText("Filtrar");
        btFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltrarActionPerformed(evt);
            }
        });

        btListar.setText("Listar todos");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfCod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(tfSerie, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(tfCor)))
                            .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btNovo)
                                .addGap(14, 14, 14)
                                .addComponent(btSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btExcluir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btFiltrar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btListar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(tfFiltro))))))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btNovo)
                    .addComponent(btExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbMarca)
                    .addComponent(rbModelo)
                    .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFiltrar)
                    .addComponent(btListar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSerieActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if(tfSerie.getText().trim().equals("") || tfCor.getText().trim().equals("")
                || tfCod.getText().trim().equals("") || tfEstado.getText().trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{
        
            pneu = new Pneu();
            pneu.setSeriePneu(tfSerie.getText());
            pneu.setCorPneu(tfCor.getText());
            pneu.setCodPneu(Integer.parseInt(tfCod.getText()));
            pneu.setEstadoPneu(tfEstado.getText());
            if(tfID.getText().equals("")){
                daoPneu.inserir(pneu);
            }else{
                pneu.setId(Integer.parseInt(tfID.getText()));
                daoPneu.atualziarPneu(pneu);
            }
            this.atualizarTabela();
            this.limparCampos();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEstadoFocusLost
        try{
            int i = Integer.parseInt(tfEstado.getText());
        }catch(NumberFormatException e){
            tfEstado.setText("");
            JOptionPane.showMessageDialog(null, "O ano deve ser um número inteiro.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tfEstadoFocusLost

    private void jtPneusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPneusMouseClicked
        tfID.setText(
                jtPneus.getValueAt(jtPneus.getSelectedRow(), 
                        VeiculoTableModel.COL_CODIGO).toString()
        );
        tfSerie.setText(
                jtPneus.getValueAt(jtPneus.getSelectedRow(), 
                        VeiculoTableModel.COL_MARCA).toString()
        );
        tfCor.setText(
                jtPneus.getValueAt(jtPneus.getSelectedRow(), 
                        VeiculoTableModel.COL_MODELO).toString()
        );
        tfCod.setText(
                jtPneus.getValueAt(jtPneus.getSelectedRow(), 
                        VeiculoTableModel.COL_CHASSI).toString()
        );
        tfEstado.setText(
                jtPneus.getValueAt(jtPneus.getSelectedRow(), 
                        VeiculoTableModel.COL_ANO).toString()
        );
        btExcluir.setEnabled(true);
    }//GEN-LAST:event_jtPneusMouseClicked

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        this.limparCampos();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Confrma a exclusão?",
            "Exclusão de veículo", JOptionPane.YES_NO_OPTION);
        
        //System.out.println("confirma = " + confirma);
        if(confirma == 0){
            daoPneu.deletarPneu(Integer.parseInt(tfID.getText()));
            this.limparCampos();
            this.atualizarTabela();
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void rbModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbModeloActionPerformed

    private void tfFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFiltroActionPerformed

    private void btFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltrarActionPerformed
        String campo = "";
        if(rbMarca.isSelected()){
            campo = "marca";
        }else{
            campo = "modelo";
        }
        
        jtPneus.setModel(new VeiculoTableModel(
                daoVeiculo.buscarTodosFiltro(campo, tfFiltro.getText())));
        this.limparCampos();
    }//GEN-LAST:event_btFiltrarActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        this.limparCampos();
        this.atualizarTabela();
    }//GEN-LAST:event_btListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PneuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFiltro;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFiltrar;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPneus;
    private javax.swing.JRadioButton rbMarca;
    private javax.swing.JRadioButton rbModelo;
    private javax.swing.JTextField tfCod;
    private javax.swing.JTextField tfCor;
    private javax.swing.JTextField tfEstado;
    private javax.swing.JTextField tfFiltro;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfSerie;
    // End of variables declaration//GEN-END:variables
}
